# Generated by Django 2.2.3 on 2019-07-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
