# Generated by Django 2.2.3 on 2019-07-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desc',
            new_name='description',
        ),
    ]
